export const SEND_PROMPT_ATTEMPT = 'SEND_PROMPT_ATTEMPT'
export const SEND_PROMPT_SUCCESS = 'SEND_PROMPT_SUCCESS'
export const SEND_PROMPT_FAILURE = 'SEND_PROMPT_FAILURE'

export const FETCH_USERS_ATTEMPT = 'FETCH_USERS_ATTEMPT'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
