export const SEND_PROMPT_ATTEMPT = 'SEND_PROMPT_ATTEMPT'
export const SEND_PROMPT_SUCCESS = 'SEND_PROMPT_SUCCESS'
export const SEND_PROMPT_FAILURE = 'SEND_PROMPT_FAILURE'

export const FETCH_USERS_ATTEMPT = 'FETCH_USERS_ATTEMPT'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const CREATE_USER_ATTEMPT = 'CREATE_USER_ATTEMPT'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const CREATE_PAIR_ATTEMPT = 'CREATE_PAIR_ATTEMPT'
export const CREATE_PAIR_SUCCESS = 'CREATE_PAIR_SUCCESS'
export const CREATE_PAIR_FAILURE = 'CREATE_PAIR_FAILURE'
